<?php

/**
 * Admin sidebar navigation structure.
 *
 * Groups use Phoenix dropdown-indicator / Bootstrap collapse patterns.
 * Permissions mirror routes/admin.php middleware — items are filtered at render time.
 *
 * Search metadata (keywords, aliases, priority, subtitle, breadcrumb) is co-located
 * here so navigation and search stay in sync automatically. The AdminSearchIndex
 * service reads this config alongside config/admin-search-index.php (actions only).
 *
 * Search fields:
 *   keywords  — array of extra search terms (do not repeat the label)
 *   aliases   — alternate names users might type (e.g. "items" for Products)
 *   subtitle  — one-line description shown below the result title
 *   breadcrumb — navigation path shown in the result (e.g. "Catalog > Products")
 *   priority  — 0–100 integer; higher = appears sooner in results (default: 50)
 *   search    — false to exclude this entry from search entirely
 */
return [
    [
        'type'       => 'link',
        'label'      => 'Dashboard',
        'route'      => 'admin.dashboard',
        'icon'       => 'pie-chart',
        'active'     => ['admin.dashboard'],
        // search metadata
        'subtitle'   => 'Overview, KPIs, and quick stats',
        'breadcrumb' => 'Dashboard',
        'keywords'   => ['home', 'overview', 'kpi', 'stats', 'summary', 'metrics'],
        'aliases'    => ['home', 'main'],
        'priority'   => 95,
    ],
    [
        'type'       => 'group',
        'id'         => 'nv-catalog',
        'label'      => 'Catalog',
        'icon'       => 'box',
        'permission' => 'manage_products',
        // group-level search metadata (the group itself is not searchable; only items are)
        'items'      => [
            [
                'label'      => 'Products',
                'route'      => 'admin.products.index',
                'active'     => ['admin.products.*'],
                'subtitle'   => 'Manage all products in your catalog',
                'breadcrumb' => 'Catalog > Products',
                'keywords'   => ['catalog', 'sku', 'listing', 'goods', 'merchandise', 'shop'],
                'aliases'    => ['items', 'goods', 'merchandise', 'listings'],
                'priority'   => 90,
            ],
            [
                'label'      => 'Inventory',
                'route'      => 'admin.inventory.index',
                'active'     => ['admin.inventory.*'],
                'subtitle'   => 'Track and adjust stock levels',
                'breadcrumb' => 'Catalog > Inventory',
                'keywords'   => ['stock', 'quantity', 'warehouse', 'levels', 'adjustments', 'variants'],
                'aliases'    => ['stock', 'warehouse', 'quantities'],
                'priority'   => 85,
            ],
            [
                'label'      => 'Categories',
                'route'      => 'admin.categories.index',
                'active'     => ['admin.categories.*'],
                'subtitle'   => 'Organize products into hierarchical categories',
                'breadcrumb' => 'Catalog > Categories',
                'keywords'   => ['taxonomy', 'classification', 'groups', 'tree', 'hierarchy'],
                'aliases'    => ['taxonomy', 'classification'],
                'priority'   => 80,
            ],
            [
                'label'      => 'Reviews',
                'route'      => 'admin.reviews.index',
                'active'     => ['admin.reviews.*'],
                'subtitle'   => 'Moderate customer product reviews',
                'breadcrumb' => 'Catalog > Reviews',
                'keywords'   => ['ratings', 'feedback', 'moderation', 'approve', 'reject', 'testimonials'],
                'aliases'    => ['ratings', 'testimonials', 'feedback'],
                'priority'   => 60,
            ],
            [
                'label'      => 'Campaigns',
                'route'      => 'admin.campaigns.index',
                'active'     => ['admin.campaigns.*'],
                'subtitle'   => 'Create and manage time-limited sales campaigns',
                'breadcrumb' => 'Catalog > Campaigns',
                'keywords'   => ['sale', 'promo', 'event', 'flash sale', 'deal', 'seasonal'],
                'aliases'    => ['sale', 'promo', 'event', 'promotions'],
                'priority'   => 80,
            ],
            [
                'label'      => 'Pages',
                'route'      => 'admin.pages.index',
                'active'     => ['admin.pages.*'],
                'subtitle'   => 'Manage storefront CMS pages and landing pages',
                'breadcrumb' => 'Catalog > Pages',
                'keywords'   => ['cms', 'landing', 'content', 'static page', 'storefront'],
                'aliases'    => ['cms pages', 'landing pages', 'content pages'],
                'priority'   => 65,
            ],
            [
                'label'      => 'Collections',
                'route'      => 'admin.collections.index',
                'active'     => ['admin.collections.*'],
                'subtitle'   => 'Curated product groupings for merchandising',
                'breadcrumb' => 'Catalog > Collections',
                'keywords'   => ['curated', 'featured', 'groups', 'product sets'],
                'aliases'    => ['featured products', 'product groups'],
                'priority'   => 65,
            ],
            [
                'label'      => 'Banners',
                'route'      => 'admin.banners.index',
                'active'     => ['admin.banners.*'],
                'subtitle'   => 'Homepage and promotional banner management',
                'breadcrumb' => 'Catalog > Banners',
                'keywords'   => ['hero', 'slider', 'image', 'homepage banner', 'ads', 'carousel'],
                'aliases'    => ['hero images', 'sliders', 'ads'],
                'priority'   => 65,
            ],
            [
                'label'      => 'Coupons',
                'route'      => 'admin.coupons.index',
                'active'     => ['admin.coupons.*'],
                'subtitle'   => 'Discount codes and coupon management',
                'breadcrumb' => 'Catalog > Coupons',
                'keywords'   => ['discount', 'promo code', 'voucher', 'redemption', 'code'],
                'aliases'    => ['discount codes', 'vouchers', 'promo codes'],
                'priority'   => 75,
            ],
            [
                'label'      => 'Sale prices',
                'route'      => 'admin.promotions.index',
                'active'     => ['admin.promotions.*'],
                'subtitle'   => 'Scheduled promotional pricing on products',
                'breadcrumb' => 'Catalog > Sale Prices',
                'keywords'   => ['promotions', 'discount price', 'flash price', 'scheduled price', 'sale'],
                'aliases'    => ['promotions', 'promotional pricing', 'discounts'],
                'priority'   => 70,
            ],
            [
                'label'      => 'Bulk pricing',
                'route'      => 'admin.pricing.bulk.create',
                'active'     => ['admin.pricing.bulk.*'],
                'subtitle'   => 'Adjust prices across categories or whole catalog',
                'breadcrumb' => 'Catalog > Bulk Pricing',
                'keywords'   => ['mass price', 'price adjustment', 'catalog pricing', 'bulk discount'],
                'aliases'    => ['mass pricing', 'price adjustment', 'catalog pricing'],
                'priority'   => 55,
            ],
        ],
    ],
    [
        'type'       => 'group',
        'id'         => 'nv-orders',
        'label'      => 'Orders & fulfillment',
        'icon'       => 'shopping-cart',
        'permission' => ['manage_orders', 'manage_returns', 'manage_refunds'],
        'items'      => [
            [
                'label'      => 'Orders',
                'route'      => 'admin.orders.index',
                'active'     => ['admin.orders.*'],
                'permission' => 'manage_orders',
                'subtitle'   => 'View and manage all customer orders',
                'breadcrumb' => 'Orders & Fulfillment > Orders',
                'keywords'   => ['purchase', 'transaction', 'checkout', 'order list', 'sales'],
                'aliases'    => ['purchases', 'transactions', 'sales'],
                'priority'   => 90,
            ],
            [
                'label'      => 'Logistics Hub',
                'route'      => 'admin.logistics.index',
                'active'     => ['admin.logistics.index'],
                'permission' => 'manage_orders',
                'subtitle'   => 'Dispatch console and fulfillment overview',
                'breadcrumb' => 'Orders & Fulfillment > Logistics',
                'keywords'   => ['dispatch', 'fulfillment', 'shipping', 'delivery', 'hub'],
                'aliases'    => ['dispatch', 'fulfillment center'],
                'priority'   => 70,
            ],
            [
                'label'      => 'Shipments',
                'route'      => 'admin.shipments.index',
                'active'     => ['admin.shipments.*'],
                'permission' => 'manage_orders',
                'subtitle'   => 'Track and advance shipment statuses',
                'breadcrumb' => 'Orders & Fulfillment > Shipments',
                'keywords'   => ['tracking', 'courier', 'parcel', 'delivery', 'dispatch'],
                'aliases'    => ['parcels', 'tracking', 'deliveries'],
                'priority'   => 75,
            ],
            [
                'label'      => 'Delivery Zones',
                'route'      => 'admin.delivery-zones.index',
                'active'     => ['admin.delivery-zones.*'],
                'permission' => 'manage_orders',
                'subtitle'   => 'Define geographic delivery zones and rates',
                'breadcrumb' => 'Orders & Fulfillment > Delivery Zones',
                'keywords'   => ['shipping zones', 'coverage', 'geography', 'rates', 'regions'],
                'aliases'    => ['shipping zones', 'coverage areas', 'delivery regions'],
                'priority'   => 60,
            ],
            [
                'label'      => 'Locations',
                'route'      => 'admin.locations.index',
                'active'     => ['admin.locations.*'],
                'permission' => 'manage_orders',
                'subtitle'   => 'Manage warehouses and pickup locations',
                'breadcrumb' => 'Orders & Fulfillment > Locations',
                'keywords'   => ['warehouse', 'pickup', 'address', 'store location', 'depot'],
                'aliases'    => ['warehouses', 'pickup points', 'depots'],
                'priority'   => 60,
            ],
            [
                'label'      => 'Returns',
                'route'      => 'admin.returns.index',
                'active'     => ['admin.returns.*'],
                'permission' => 'manage_returns',
                'subtitle'   => 'Process customer return requests and inspections',
                'breadcrumb' => 'Orders & Fulfillment > Returns',
                'keywords'   => ['refund', 'rma', 'return request', 'reverse logistics', 'exchange'],
                'aliases'    => ['rma', 'return requests', 'exchanges'],
                'priority'   => 75,
            ],
            [
                'label'      => 'Store credit',
                'route'      => 'admin.store-credits.index',
                'active'     => ['admin.store-credits.*'],
                'permission' => 'manage_refunds',
                'icon'       => 'award',
                'subtitle'   => 'Issue and manage customer store credits',
                'breadcrumb' => 'Orders & Fulfillment > Store Credit',
                'keywords'   => ['wallet', 'credit', 'refund credit', 'balance', 'compensation'],
                'aliases'    => ['wallet credits', 'customer balance'],
                'priority'   => 65,
            ],
        ],
    ],
    [
        'type'       => 'group',
        'id'         => 'nv-finance',
        'label'      => 'Finance',
        'icon'       => 'credit-card',
        'permission' => 'manage_payments',
        'items'      => [
            [
                'label'      => 'Payments',
                'route'      => 'admin.payments.index',
                'active'     => ['admin.payments.index', 'admin.payments.*'],
                'subtitle'   => 'Payment verification and reconciliation',
                'breadcrumb' => 'Finance > Payments',
                'keywords'   => ['transactions', 'gateway', 'verify', 'payment list', 'billing'],
                'aliases'    => ['billing', 'payment transactions'],
                'priority'   => 80,
            ],
            [
                'label'      => 'Transfers',
                'route'      => 'admin.transfers.index',
                'active'     => ['admin.transfers.*'],
                'subtitle'   => 'Manual bank transfer reconciliation',
                'breadcrumb' => 'Finance > Transfers',
                'keywords'   => ['bank transfer', 'wire', 'manual payment', 'bank slip', 'reconcile'],
                'aliases'    => ['bank transfers', 'wire transfers'],
                'priority'   => 65,
            ],
            [
                'label'      => 'Reconciliation',
                'route'      => 'admin.reconciliation',
                'active'     => ['admin.reconciliation'],
                'subtitle'   => 'Daily payment reconciliation report',
                'breadcrumb' => 'Finance > Reconciliation',
                'keywords'   => ['daily report', 'financial', 'settlement', 'eod', 'end of day'],
                'aliases'    => ['daily report', 'settlement report'],
                'priority'   => 60,
            ],
        ],
    ],
    [
        'type'       => 'section',
        'label'      => 'Insights',
        'permission' => 'view_analytics',
        'search'     => false, // section labels not searchable
    ],
    [
        'type'       => 'link',
        'label'      => 'Analytics',
        'route'      => 'admin.analytics',
        'icon'       => 'bar-chart-2',
        'active'     => ['admin.analytics'],
        'permission' => 'view_analytics',
        'subtitle'   => 'Sales analytics, revenue reports, and insights',
        'breadcrumb' => 'Insights > Analytics',
        'keywords'   => ['reports', 'revenue', 'charts', 'graphs', 'data', 'kpi', 'sales data'],
        'aliases'    => ['reports', 'revenue analytics', 'insights', 'statistics'],
        'priority'   => 85,
    ],
    [
        'type'       => 'section',
        'label'      => 'People',
        'permission' => 'manage_customers',
        'search'     => false,
    ],
    [
        'type'       => 'group',
        'id'         => 'nv-people',
        'label'      => 'Customers',
        'icon'       => 'users',
        'permission' => 'manage_customers',
        'items'      => [
            [
                'label'      => 'All customers',
                'route'      => 'admin.customers.index',
                'active'     => ['admin.customers.*'],
                'subtitle'   => 'Browse and manage customer accounts',
                'breadcrumb' => 'Customers > All Customers',
                'keywords'   => ['users', 'buyer', 'accounts', 'crm', 'customer list'],
                'aliases'    => ['users', 'buyers', 'crm', 'clients'],
                'priority'   => 85,
            ],
            [
                'label'      => 'Wholesale',
                'route'      => 'admin.wholesale.index',
                'active'     => ['admin.wholesale.*'],
                'subtitle'   => 'Manage wholesale customer applications',
                'breadcrumb' => 'Customers > Wholesale',
                'keywords'   => ['b2b', 'bulk buyer', 'trade', 'wholesale approval'],
                'aliases'    => ['b2b', 'trade customers'],
                'priority'   => 60,
            ],
            [
                'label'      => 'Bulk requests',
                'route'      => 'admin.bulk-requests.index',
                'active'     => ['admin.bulk-requests.*'],
                'subtitle'   => 'Bulk quantity leads from product pages',
                'breadcrumb' => 'Customers > Bulk Requests',
                'keywords'   => ['rfq', 'quote', 'bulk order request', 'large order'],
                'aliases'    => ['rfq', 'quote requests'],
                'priority'   => 55,
            ],
        ],
    ],

    // Owner-only: staff & role management.
    [
        'type'        => 'group',
        'id'          => 'nv-team',
        'label'       => 'Team',
        'icon'        => 'shield',
        'super_admin' => true,
        'items'       => [
            [
                'label'      => 'Staff',
                'route'      => 'admin.staff.index',
                'active'     => ['admin.staff.*'],
                'icon'       => 'user-check',
                'subtitle'   => 'Manage admin staff accounts and access',
                'breadcrumb' => 'Team > Staff',
                'keywords'   => ['team', 'admins', 'users', 'employees', 'invite', 'members'],
                'aliases'    => ['admins', 'team members', 'employees'],
                'priority'   => 75,
            ],
            [
                'label'      => 'Roles',
                'route'      => 'admin.roles.index',
                'active'     => ['admin.roles.*'],
                'icon'       => 'shield',
                'subtitle'   => 'Configure permission roles and access levels',
                'breadcrumb' => 'Team > Roles',
                'keywords'   => ['permissions', 'access control', 'rbac', 'acl', 'authorization'],
                'aliases'    => ['permissions', 'access control', 'rbac'],
                'priority'   => 70,
            ],
            [
                'label'      => 'Activity log',
                'route'      => 'admin.activity.index',
                'active'     => ['admin.activity.*'],
                'icon'       => 'activity',
                'subtitle'   => 'Audit trail of admin actions',
                'breadcrumb' => 'Team > Activity Log',
                'keywords'   => ['audit', 'history', 'logs', 'trail', 'security log', 'actions'],
                'aliases'    => ['audit trail', 'audit log', 'security log'],
                'priority'   => 65,
            ],
        ],
    ],

    // Settings — personal account (always accessible to authenticated admins)
    [
        'type'       => 'link',
        'label'      => 'Account Settings',
        'route'      => 'admin.settings',
        'icon'       => 'user',
        'active'     => ['admin.settings'],
        'search'     => true, // shown in search even though not in sidebar
        'sidebar'    => false, // hide from sidebar nav
        'subtitle'   => 'Personal profile, password, and 2FA settings',
        'breadcrumb' => 'Settings > Account',
        'keywords'   => ['profile', 'password', 'security', '2fa', 'two factor', 'personal'],
        'aliases'    => ['my profile', 'my account', 'profile settings'],
        'priority'   => 70,
    ],

    // Store settings — super admin only
    [
        'type'        => 'link',
        'label'       => 'Store Settings',
        'route'       => 'admin.settings.store',
        'icon'        => 'shopping-bag',
        'active'      => ['admin.settings.store'],
        'super_admin' => true,
        'search'      => true,
        'sidebar'     => false,
        'subtitle'    => 'General store configuration, branding, and policies',
        'breadcrumb'  => 'Settings > Store',
        'keywords'    => ['configuration', 'store config', 'branding', 'general settings', 'policies'],
        'aliases'     => ['store config', 'general settings', 'shop settings'],
        'priority'    => 80,
    ],

    // Notifications — available to every admin
    [
        'type'     => 'link',
        'label'    => 'Notifications',
        'route'    => 'admin.notifications.index',
        'icon'     => 'bell',
        'active'   => ['admin.notifications.*'],
        'search'   => true,
        'sidebar'  => false,
        'subtitle' => 'All admin notifications and alerts',
        'breadcrumb' => 'Notifications',
        'keywords' => ['alerts', 'messages', 'inbox', 'updates'],
        'aliases'  => ['alerts', 'inbox'],
        'priority' => 60,
    ],

    // Inventory Import — sub-page, not in sidebar
    [
        'type'       => 'link',
        'label'      => 'Import Inventory',
        'route'      => 'admin.inventory.import.create',
        'icon'       => 'upload',
        'active'     => ['admin.inventory.import.*'],
        'permission' => 'manage_products',
        'search'     => true,
        'sidebar'    => false,
        'subtitle'   => 'Bulk import stock levels via CSV or spreadsheet',
        'breadcrumb' => 'Catalog > Inventory > Import',
        'keywords'   => ['csv import', 'bulk upload', 'stock import', 'spreadsheet', 'data import'],
        'aliases'    => ['stock import', 'csv upload', 'bulk import'],
        'priority'   => 60,
    ],

    // Merchandising — commented out in sidebar but kept searchable
    [
        'type'       => 'link',
        'label'      => 'Merchandising',
        'route'      => 'admin.merchandising.index',
        'icon'       => 'layout',
        'active'     => ['admin.merchandising.*'],
        'permission' => 'manage_products',
        'search'     => true,
        'sidebar'    => false,
        'subtitle'   => 'Homepage sections and storefront layout builder',
        'breadcrumb' => 'Catalog > Merchandising',
        'keywords'   => ['homepage', 'sections', 'layout', 'storefront builder', 'featured'],
        'aliases'    => ['homepage builder', 'storefront sections'],
        'priority'   => 65,
    ],
];
